version: "3.8"

services:
  redis:
    image: "redis:6"
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50

  minio:
    image: "minio/minio"
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  qa_medical_bot_api:
    build: .
    container_name: qa_medical_bot_api
    ports:
      - "8000:8000"
    env_file: 
      - .env
    volumes:
      - .:/app
    restart: always

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A src.upload_process.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  minio_data: